---
- name: Set kibana_system password in Elasticsearch with SSL validation
  hosts: localhost
  vars:
    ca_path: "../ElasticConfig/Elasticsearch/certificates/ca-cert.pem"  # Path to your CA bundle

  tasks:
    - name: Set kibana_system user password
      uri:
        url: "https://es01.mustard.ovh:9200/_security/user/kibana_system/_password"
        method: POST
        user: "elastic" # elastic is used to authenticate, Kibana system is account we are setting password for
        password: "demo-password123222"
        body_format: json
        body: '{"password": "demo-password123222"}'
        headers:
          Content-Type: "application/json"
        status_code: 200
        validate_certs: no
        force_basic_auth: no
      register: response

    - name: Print response for debugging
      debug:
        var: response
